config/routes.rb
Rails.application.routes.draw do
  get 'privacy/index'
  get 'home/index'
  get 'projects', to: 'projects#index'
  get 'projects/:project_url', to: 'projects#index'
  get 'privacy', to: 'privacy#index'

  post 'handle_contact_request', to: 'home#handle_contact_request'

  root 'home#index'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  invisible_captcha only: [:create, :update], honeypot: :subtitle

  def index
  end

  def handle_contact_request
    ActionMailer::Base.mail(from: "#{params['form-name']} <#{params['form-email']}>", to: Rails.application.credentials.contact_form_to, subject: "Neue Kontaktanfrage auf deiner Homepage", body: "#{params['form-text']}\n\nTelefon: #{params['form-phone']}").deliver
    redirect_to root_path(:anchor => 'contact'), notice: "I'll reply shortly. Here's what you wrote:\n #{params['form-text']} \n"
  end
end

app/controllers/privacy_controller.rb
class PrivacyController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
def index
  @projects = Project.all
end

def show
end

private

def find_project
  @project = Project.find(params[:url])
end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/_about.html.erb
<div class="uk-width-expand">
  <h2>Welcome to my website!</h2>
  <p>It's under construction at the moment. Please come back later to see my latest projects.</p>
</div><!-- end main-text -->
  
<div class="uk-width-1-3@m">
  <h2>I've illustrated for... </h2>
  <div id="client-list">
    <span>Thomas Cook Hotels and Resorts</span>
    <span>Bäckerei Wolf</span>
    <span>Azubiyo</span>
    <span>Oldenbourg Schulbuchverlag</span>
    <span>Jetzt Magazin (Süddeutsche Zeitung)</span>                     
    <span>Sentido </span>
  </div>
  <div id="awards">
    <%= image_tag("DDC_WinnerBadget_DE4_Bronze-11.svg", id:"DDC-img") %>
    <small>Award in the Deutscher Designer Club DDC competition for the <%= link_to "Büroecco", "https://bueroecco.com/" %> <%= link_to "bird postcards", projects_path %> project</small>
  </div>
</div><!-- end skills -->

app/views/home/_contact.html.erb
<div class="uk-width-2-3@m">
  <div id="map"></div>
</div>

<div class="uk-width-1-3@m" id="address">  
    <h2>Contact info</h2>
    <ul>
      <span uk-icon="icon: mail"></span><li> mail[at]judithurban.de</li></br>
    </ul>
  </div>
  <div class="uk-width-2-3@m">
    <h2>Get in touch!</h2>
    <p>
      At the moment, I'm only free for illustrative projects. Let's chat about things, just give me a call or drop me an email.
    </p>


  </div>

app/views/home/_faq.html.erb
<div class="row-wrap-inline">
  <h2 id="portfolio-head">My approach to creating things</h2>
</div>

<ul uk-accordion>
  <li class="uk-open">
    <a class="uk-accordion-title accordion-title" href="#">Web Development</a>
    <div class="uk-accordion-content accordion-content">
      <p>As someone who's started out in the creative sector, I've internalized the design thinking approach. I've developed my skillset to embrace web technology (HTML, CSS, JavaScript) and I rely on best practise to get things done efficiently. 
      </p>
    </div>
  </li>
  <li>
  <a class="uk-accordion-title" href="#">Creative Consulting</a>
  <div class="uk-accordion-content accordion-content">
    <p>How does that fit together with design? Every online and offline experience that is worth a second look has been carefully designed. For me, being creative involves pinning information down to the key contents. I always look for the intuitive structure that works best for users.
    </p>
  </div>
  </li>
  <li>
    <a class="uk-accordion-title" href="#">Illustration: Book me!</a>
    <div class="uk-accordion-content accordion-content">
      <p>Illustrations have the power to visualize things more directly. They can make a visual presence really outstanding. As a freelancer I am specialized in high-quality digital illustrations that and blend in perfectly with a given corporate design. Do you have a project in mind? <%= link_to "Get in touch", root_path(:anchor => 'contact'), :"data-uk-smooth-scroll" => true, :class => "page-anchor" %> and let's turn the talk into the walk. </p>
    </div>
  </li>
</ul>

app/views/home/index.html.erb
    <section class="jumbotron">
      <h1>The art of bug whispering.</h1>
      <p>
        Hi! I'm Judith, artist and web developer. I create engaging illustrative and interactive experiences.
      </p>
      <a href="/#about" uk-icon="icon: chevron-down" class="arrow bounce" data-uk-smooth-scroll="true"></a>
    </section><!-- section -->

    <div class="container anchor" id="about" uk-grid>
      <%= render partial: "about" %>
    </div><!-- end container -->

    <div class="container anchor" id="faq">
      <%= render partial: "faq" %>
    </div> <!-- end container -->

    <div class="container anchor" id="contact"uk-grid>
      <%= render partial: "contact" %>
    </div><!-- end container -->
    <%= javascript_include_tag 'home' %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBlaXHm--EpRXmMQrLBBQXadKU8L8RgXQ8&callback=initMap"
    defer></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title>Judiths Portfolio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:300|Rubik:500" rel="stylesheet">
     <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.10/css/uikit.min.css" />
    <!-- UIkit JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.10/js/uikit.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.10/js/uikit-icons.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


</head>


  <body>
    <nav>
      <div class="header-items-all">
        <%= link_to image_tag("ju.svg"), root_path, {id: 'logo', alt: 'Judiths Logo'} %>
        <span class="navbar-link-toggle" uk-icon="icon: table" aria-hidden="true"></span>
        <ul class="header-items-list header-items-list-hidden" uk-scrollspy-nav="closest: li; scroll: true">
          <li><%= link_to "about", root_path(:anchor => 'about'), :"data-uk-smooth-scroll" => true, :class => "page-anchor" %></li>
          <li><%= link_to "contact", root_path(:anchor => 'contact'), :"data-uk-smooth-scroll" => true, :class => "page-anchor" %></li>
        </ul>
      </div>
    </nav>
    <%= yield %>
    </div>

    <footer>
      <div id="privacy"><%= link_to "Privacy Policy", privacy_path %></div>
      <div>&copy; Judith Urban</div>
    </footer>
  </body>
</html>

app/views/projects/_pf-item.html.erb
<div id="pf-item<%= project.id %>" class="pf-item">
  <div class="pf-project-box">
    <button class="pf-close-button"><span uk-icon="icon: close" class="uk-icon-large"></span></button>
    <div class="pf-text-box uk-width-2-3@m">
      <h2><%= project.title %></h2>
      <p><%= project.description %></p>
    </div>
    <div class="pf-image-box">
    <% project.images.each do |image| %>
      <%= image_tag(image.url, class: "pf-image #{image.css_class}", alt:image.title) %>
    <% end %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
    <section class="pf-section">
    <div id="clickdrag"><%= image_tag("drag.svg") %></div>
    <% @projects.each do |project| %>
      <%= image_tag(project.preview_image, class: "pf-prevbox", id:"pf-prevbox-item#{project.id}", draggable:"false", data: { link: "pf-item#{project.id}", url: project.url}) %>
    <% end %>
    </section>
    <% @projects.each do |project| %>
    <%= render partial: 'pf-item', locals: {project: project} %>
    <% end %>
    <%= javascript_include_tag 'projects' %>

app/views/simple_pages/_about.html.erb
<div class="uk-width-expand">
  <h2>Artist and nerd ...</h2>
  <p>...These are my two best sides. I also have a love for mushroom hunting, a big pile of indie games (with a note that says „to be reviewed“), a soft spot for my big ugly double bass, and the ability to speak four and a half languages.</p>
  <p>I grew up in the Bavarian Forest and graduated in Augsburg and Würzburg with a Master's degree in Information Design. Since 2013, I've been working for branding agencies in Vienna and Augsburg, where I've set up traps for small and big ideas and visualized engaging analog and digital stories.</p>
  <p>I've always kept my eye out for the underbrush of the web. And I like the way the open source community works together, embracing diversity and sharing skills for a common goal. That's the reason why I set out to become a full-stack-web developer.</p>
  <p>Today, I am specialized in high-quality hand-drawn illustrations that blend in perfectly with a given corporate design. And I effectively use my expertise in the latest technology to make contents come alive.
  <%= link_to "Get in touch!", root_path(:anchor => 'contact'), :"data-uk-smooth-scroll" => true %>
</div><!-- end main-text -->
  
<div class="uk-width-1-3@m">
  <h2>A selection of recent customers</h2>
  <div id="client-list">
    <span>Thomas Cook Hotels and Resorts</span>
    <span>AHA 360°</span>
    <span>Bäckerei Wolf</span>
    <span>Azubiyo</span>
    <span>Welzhofer</span>
    <span>Oldenbourg Schulbuchverlag</span>
    <span>Jetzt Magazin (Süddeutsche Zeitung)</span>                     
    <span>Hutzelhof</span>
    <span>Sentido </span>
  </div>
</div><!-- end skills -->

app/views/simple_pages/_faq.html.erb
<div class="row-wrap-inline">
  <h2 id="portfolio-head">Learn more</h2>
  <a class="uk-button uk-button-default button" href="#modal-portfolio" uk-toggle>PDF Version of my Portfolio</a>
</div>
<div id="modal-portfolio" class="uk-modal-container" uk-modal>
  <div class="uk-modal-dialog uk-margin-auto-vertical">
    <button class="uk-modal-close-default" type="button" uk-close></button>
    <div class="uk-modal-header">
      <h3 class="uk-modal-title">Judiths Portfolio</h3>
    </div>
    <div class="uk-modal-body">
      <embed id="modal-embed" src="data/Portfolio_Judith_Urban_XS.pdf"></embed>
    </div>
  </div>
</div>

<ul uk-accordion>
  <li class="uk-open">
    <a class="uk-accordion-title accordion-title" href="#">What's your goal as a web developer?</a>
    <div class="uk-accordion-content accordion-content">
      <p>I embrace web technology and rely on best practise to get things done effectively and on time. I start with prototypes that show if things work, refining them further until they’re ready to roll out.
      </p>
    </div>
    </li>
    <li>
      <a class="uk-accordion-title" href="#">How does this go together with illustration?</a>
      <div class="uk-accordion-content accordion-content">
        <p>I get creative sketching and drawing out ideas. For my illustrations to become your eye-catchers, I use my intuition and rely on a variety of original styles. They often add the final touch that make a visual presence really outstanding.
        </p>
      </div>
  </li>
    <li>
      <a class="uk-accordion-title" href="#">I might have a project idea.</a>
      <div class="uk-accordion-content accordion-content">
        <p>Every online and offline experience that’s worth a second look has been designed. So let's meet up and turn the talk into the walk! I like to listen, take the time to find out more, to pin it all down to the key contents and get it out there. 
        </p>
      </div>
    </li>
</ul>

app/views/simple_pages/index.html.erb
    <section class="jumbotron">
      <h1>The art of bug whispering.</h1>
      <p>
        Hi! I'm Judith, artist and web developer. I create engaging illustrative and interactive experiences.
      </p>
      <span uk-icon="icon: chevron-down" class="big-icon moving-icon"></span>
    </section><!-- section -->

    <div class="container anchor" id="about" uk-grid>
      <%= render partial: "about" %>
    </div><!-- end container -->

    <div class="container anchor" id="faq">
      <%= render partial: "faq" %>
    </div> <!-- end container -->

    <div class="container anchor" id="contact"uk-grid>
      <%= render partial: "contact" %>
    </div><!-- end container -->